### ISSUE TITLE
程序闪退

### ISSUE THREAD

**Issue by yun-chen-yue** [boring-design/haye-distro#1]
程序闪退后开了四个,并且每个 CPU 占用都达到了 100%+,昨天闪退的,我没有在意,今天早上电脑异常发烫,我打开了活动监视器,发现CPU 占用拉满了

**Comment by hi-caicai** [comment]
有其他补充信息么？我们来排查下

**Comment by yun-chen-yue** [comment]
假定软件打开的路径为 A
打开软件后,我把软件移到了 A/a
闪退后点击了重启,无任何反应,当时没在意
后续电脑异常发烫,才发现程序启动了四个,并且每个 CPU 占用都为 100+
当时忘了截图
电脑是 M1pro
下次我可以截下图

**Comment by hi-caicai** [comment]
软件打开的路径为 A，打开软件后,我把软件移到了 A/a 这个我很好奇，这是啥操作？

**Comment by yun-chen-yue** [comment]
下载完之后在我的下载这个目录下,解压后直接打开了,程序正常运行之后,我将软件包归档到了我的软件
<img width="770" alt="image" src="https://github.com/boring-design/haye-distro/assets/80777335/d125bc92-fc28-4b19-934d-a5b9d482aba2">





------ 补充

现在移动应用程序到别的目录已无法通过 command + E 唤起程序,移回来可以

**Comment by hi-caicai** [comment]
OK，我模拟下，btw，你不移动到 Applications 里么

**Comment by yun-chen-yue** [comment]
我喜欢把一些工具收在一起

**Comment by hi-caicai** [comment]
我们已经推送了一个版本，你到时候更新实时看，还有问题再反馈给我们哈

**Comment by yun-chen-yue** [comment]
好的
